services:
  fast-docs:
    build:
      context: /fast-docs
      dockerfile: /Dockerfile
    container_name: fast-docs
    ports:
      - 8080:8080
    networks:
      backend:
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "best_password"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database-data:/var/lib/postgresql/data
    ports:
      - 0:5432
    networks:
      - postgres_net
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: "best_password"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: "root@mail.ru"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres_net
    ports:
      - 5050:80


networks:
  backend:
  postgres_net:


volumes:
  pgadmin-data:
  database-data: